name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    timeout-minutes: 30

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD

      - name: setup-github-release
        run: sed -i -e 's/<\/servers>/<server><id>github<\/id><username>x-access-token<\/username><password>${GITHUB_TOKEN}<\/password><\/server><\/servers>/g' /home/runner/.m2/settings.xml

      - name: setup-gpg
        env:
          GPG_PRIVATE_KEY: ${{ secrets.OS_GPG_PRIVATE_KEY }}
        run: cat <(echo -e "${GPG_PRIVATE_KEY}") | gpg --batch --import

      - name: checkout
        uses: actions/checkout@v2

      - name: caching
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OS_OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OS_OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.OS_GPG_PASSPHRASE }}
        run: mvn deploy -Dmaven.wagon.http.pool=false -Dgpg.executable=gpg -Dgpg.passphrase=${GPG_PASSPHRASE}

      - name: sonar-analyse
        env:
          SONAR_HOST: ${{ secrets.OS_SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.OS_SONAR_TOKEN }}
        run: |
          export SONAR_ORGANIZATION=$(echo ${GITHUB_REPOSITORY} | cut -d / -f 1)
          mvn sonar:sonar \
            -Dsonar.host.url=${SONAR_HOST} \
            -Dsonar.login=${SONAR_TOKEN} \
            -Dsonar.organization=${SONAR_ORGANIZATION} \
            -Dsonar.projectKey=${GITHUB_REPOSITORY//\//_} \
            -Dsonar.java.binaries=./target/classes
