# This configuration is used for the pull request review
name: review

on:
  pull_request:
    # Runs only on pull request creation and on every new commit to the created pull request
    types: [opened, synchronize]

jobs:
  review:
    timeout-minutes: 30
    
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      # Setup java environment
      - name: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Checkout the git repository
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GPR_TOKEN }}
          fetch-depth: ''

      # Execute some necessary git commands to get more repository informations
      - name: post-checkout
        run: git fetch --prune --unshallow

      # Push updated GitHub Actions configuration if necessary
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: .github/workflows/*.yml
          commit_user_name: ${{ secrets.ACTIONS_CONFIG_AUTOUPDATE_USER }}
          commit_user_email: ${{ secrets.ACTIONS_CONFIG_AUTOUPDATE_EMAIL }}
          commit_author: ${{ secrets.ACTIONS_CONFIG_AUTOUPDATE_AUTHOR }}
          commit_message: Update GitHub Action configuration

      # Verify project version is updated
      - name: project-version-check
        uses: avides/actions-project-version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: pom.xml
          additional-files-to-check: README.md

      # Check if reminder comment is already given
      - name: find-reminder-comment
        uses: peter-evans/find-comment@v3
        id: find_reminder_comment
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "Confluence/GitHub documentation added or updated?"

      # Add reminder comment if not given
      - name: reminder-comment
        uses: peter-evans/create-or-update-comment@v4
        id: create
        if: ${{ steps.find_reminder_comment.outputs.comment-id == 0 }}
        with:
          body: |
            - Confluence/GitHub documentation added or updated?
              - Diff-Links as response added?
                - [ ] Not necessary
                - [ ] Added

            - [Breaking-Change](<https://avides.atlassian.net/wiki/spaces/ITENT/pages/211498/Wann+habe+ich+einen+breaking+change>) present?
              - Necessary deployment adjustments added as a comment (Jira-Ticket)?
                - [ ] Not necessary
                - [ ] Added
              - Necessary rollback adjustments added as a comment (Jira-Ticket)?
                - [ ] Not necessary
                - [ ] Added
          issue-number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup/load GitHub Actions caching for external dependencies, in this case especially for Maven
      - name: caching
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # Execute Maven command for compile and compile of the tests
      - name: compile
        run: mvn clean compile test-compile

      # Execute Unit tests
      - name: unit-tests
        run: mvn surefire:test

      # Execute Integration tests, in this case we can skip the unit tests and load these with jacoco
      - name: integration-tests
        run: mvn -DskipUTs -Dgpg.skip=true jacoco:restore-instrumented-classes verify

       # Execute sonar analysis for current branch
      - name: sonar-analyse
        env:
          SONAR_HOST: ${{ secrets.OS_SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.OS_SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export SONAR_ORGANIZATION=$(echo ${GITHUB_REPOSITORY} | cut -d / -f 1)
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar \
            -Dsonar.host.url=${SONAR_HOST} \
            -Dsonar.login=${SONAR_TOKEN} \
            -Dsonar.organization=${SONAR_ORGANIZATION} \
            -Dsonar.projectKey=${GITHUB_REPOSITORY//\//_} \
            -Dsonar.pullrequest.key=${{ github.event.number }} \
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
            -Dsonar.pullrequest.github.repository=${GITHUB_REPOSITORY} \
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} \
            -Dsonar.java.binaries=./target/classes

      # Execute Maven enforcer plugin
      - name: pom-analyse
        run: mvn enforcer:enforce
