name: review-macos

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review-macos:
    timeout-minutes: 30

    runs-on: macos-latest

    steps:
      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: checkout
        uses: actions/checkout@v2

      - name: project-version-check
        uses: avides/actions-project-version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: pom.xml
          additional-files-to-check: README.md

      - name: caching
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: compile
        run: mvn clean compile test-compile

      - name: unit-tests
        run: mvn surefire:test

      - name: integration-tests
        run: mvn -DskipUTs -Dgpg.skip=true jacoco:restore-instrumented-classes verify

      - name: pom-analyse
        run: mvn enforcer:enforce
